CREATE TYPE "Status" AS ENUM ('todo','in_progress','review','done');
CREATE TYPE "Priority" AS ENUM ('low','medium','high','urgent');
CREATE TYPE "Role" AS ENUM ('org_admin','member');
CREATE TABLE "User" ("id" TEXT NOT NULL,"email" TEXT NOT NULL,"name" TEXT NOT NULL,"passwordHash" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "User_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Organization" ("id" TEXT NOT NULL,"name" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Organization_pkey" PRIMARY KEY ("id"));
CREATE TABLE "OrgMember" ("id" TEXT NOT NULL,"userId" TEXT NOT NULL,"organizationId" TEXT NOT NULL,"role" "Role" NOT NULL DEFAULT 'member',CONSTRAINT "OrgMember_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Project" ("id" TEXT NOT NULL,"organizationId" TEXT NOT NULL,"name" TEXT NOT NULL,"description" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,"deletedAt" TIMESTAMP(3),CONSTRAINT "Project_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Task" ("id" TEXT NOT NULL,"projectId" TEXT NOT NULL,"title" TEXT NOT NULL,"description" TEXT,"status" "Status" NOT NULL DEFAULT 'todo',"priority" "Priority" NOT NULL DEFAULT 'medium',"dueDate" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,"deletedAt" TIMESTAMP(3),CONSTRAINT "Task_pkey" PRIMARY KEY ("id"));
CREATE TABLE "TaskAssignment" ("id" TEXT NOT NULL,"taskId" TEXT NOT NULL,"userId" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "TaskAssignment_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Comment" ("id" TEXT NOT NULL,"taskId" TEXT NOT NULL,"userId" TEXT NOT NULL,"body" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Comment_pkey" PRIMARY KEY ("id"));
CREATE TABLE "RefreshToken" ("id" TEXT NOT NULL,"tokenHash" TEXT NOT NULL,"userId" TEXT NOT NULL,"expiresAt" TIMESTAMP(3) NOT NULL,"revokedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "RefreshToken_pkey" PRIMARY KEY ("id"));
CREATE TABLE "JobRecord" ("id" TEXT NOT NULL,"bullJobId" TEXT NOT NULL,"type" TEXT NOT NULL,"status" TEXT NOT NULL DEFAULT 'pending',"metadata" JSONB,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "JobRecord_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "User_email_key" ON "User"("email"); CREATE UNIQUE INDEX "OrgMember_userId_organizationId_key" ON "OrgMember"("userId","organizationId"); CREATE UNIQUE INDEX "TaskAssignment_taskId_userId_key" ON "TaskAssignment"("taskId","userId"); CREATE UNIQUE INDEX "RefreshToken_tokenHash_key" ON "RefreshToken"("tokenHash"); CREATE UNIQUE INDEX "JobRecord_bullJobId_key" ON "JobRecord"("bullJobId");
CREATE INDEX "OrgMember_organizationId_role_idx" ON "OrgMember"("organizationId","role"); CREATE INDEX "Project_organizationId_createdAt_idx" ON "Project"("organizationId","createdAt"); CREATE INDEX "Project_organizationId_deletedAt_idx" ON "Project"("organizationId","deletedAt"); CREATE INDEX "Task_projectId_status_idx" ON "Task"("projectId","status"); CREATE INDEX "Task_projectId_priority_idx" ON "Task"("projectId","priority"); CREATE INDEX "Task_dueDate_idx" ON "Task"("dueDate"); CREATE INDEX "TaskAssignment_userId_idx" ON "TaskAssignment"("userId"); CREATE INDEX "Comment_taskId_createdAt_idx" ON "Comment"("taskId","createdAt"); CREATE INDEX "RefreshToken_userId_revokedAt_idx" ON "RefreshToken"("userId","revokedAt");
ALTER TABLE "OrgMember" ADD CONSTRAINT "OrgMember_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "OrgMember" ADD CONSTRAINT "OrgMember_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "Project" ADD CONSTRAINT "Project_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "Task" ADD CONSTRAINT "Task_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "TaskAssignment" ADD CONSTRAINT "TaskAssignment_taskId_fkey" FOREIGN KEY ("taskId") REFERENCES "Task"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "TaskAssignment" ADD CONSTRAINT "TaskAssignment_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "Comment" ADD CONSTRAINT "Comment_taskId_fkey" FOREIGN KEY ("taskId") REFERENCES "Task"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "Comment" ADD CONSTRAINT "Comment_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "RefreshToken" ADD CONSTRAINT "RefreshToken_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

